spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <ADD CLIENT ID>
            clientSecret: <ADD CLIENT SECRET>

          google:
            clientId: <ADD CLIENT ID>
            clientSecret: <ADD CLIENT SECRET>

server:
  port: 9191